[package]
name = "burn-mnist-explore"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = {version = "~0.15.0", features = ["train", "vision", "wgpu"]}
clap = { version = "4.5.23", features = ["derive"] }